services:
    iris:
        build: ./image-iris
        environment:
            IRIS_USERNAME: superuser
            IRIS_PASSWORD: SYS
        hostname: 2024demo
        container_name: fhirvalidation
        ports:
            - 1980:1972 
            - 52880:52773
        command: --check-caps false --ISCAgent false --log /usr/irissys/mgr/messages.log
        

